### ISSUE TITLE
GM Targeting not displaying selected Token

### ISSUE THREAD

**Issue by thetenthdemon** [theripper93/Smart-Target#6]
With the below options enabled, as the GM, I should see the targeter's controlled token on/above the target's token. It currently displays only the target indicator, optionally with the GM's color. This makes it impossible to differentiate which of the GM's creatures is targeting another creature or player.
![image](https://user-images.githubusercontent.com/85645467/121418270-667ccc00-c930-11eb-8988-79ea7ee67dd4.png)

**Comment by theripper93** [comment]
that is intended, adding the controlled token to the mix would require a lot of work and it's not a feature i'm planning to add any time soon since my focus is on other modules

**Comment by pdf** [comment]
You could simply display the standard pip, or coloured circle with no image insert for GM targeting. I had been considering deprecating `Better Target` in favour of this module (as `Target Enhancements` has recently done) since I had no intention of expanding functionlity for that module, but if this module is on life-support perhaps that's not the best course of action.

**Comment by sPOiDar** [comment]
You could simply display the standard pip, or coloured circle with no image insert for GM targeting. I had been considering deprecating Better Target in favour of this module (as Target Enhancements has recently done) since I had no intention of expanding functionlity for that module, but if this module is on life-support perhaps that's not the best course of action.

**Comment by theripper93** [comment]
it's not on life support i'm just not adding big features :P . That suggestion is way more reasonable

**Comment by sPOiDar** [comment]
Actually, I only skimmed the OP's request and see now that they were receiving GM target indicators, but wanted the token icon too - that is indeed likely not possible in any sensible way, since targeting is done per-user and there's no link between attacker and target.

In my testing, I have a different bug where no GM target pips are shown at all. Would you prefer a separate issue for that?

**Comment by theripper93** [comment]
yep please go ahead
